### PR TITLE
Update Coreum registry

### PR DESCRIPTION
**Pull request by dzmitryhil**
* Update Coreum mainnet to v3.0.3
* Update Coreum testnet to v3.0.3
* Add testnet upgrade history

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/chain-registry/1)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/chain-registry/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu, @wanesurf, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/chain-registry/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu, @wanesurf, and @wojtek-coreum)

**Review by keyleu — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/chain-registry/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wanesurf and @wojtek-coreum)

**Review by keyleu — APPROVED** [review]

**Comment by dzmitryhil** [comment]
Recreated - https://github.com/cosmos/chain-registry/pull/4607

**Pull request closed without merging**
